[
    'logistics performance index',
    'rail usage',
    'traffic-related death rate',
    'rail transport network size',
    'vehicles per capita',
    'waterways length',
    'road network size',
    'number of heliports',
    'merchant navy capacity',
    'length of pipelines',
    'international telecommunication union',
    'economist intelligence unit',
    'internet connection speeds',
    '4g lte penetration',
    'mobile banking usage',
    'smartphone penetration',
    'stem cell research trials',
    'broadband internet subscriptions',
    'space competitiveness index',
    'web index',
    'number of mobile phones in use',
    'number of telephone lines in use',
    'internet censorship and surveillance',
    'number of internet hosts',
    'ipv4 address allocation',
    'number of internet users',
    'number of television broadcast stations',
    'government broadband index',
    'ict development index',
    'networked readiness index',
    'dashboard of sustainability',
    'globalization',
    'global gender gap report',
    'global retirement index',
    'legatum prosperity index',
    'save the children',
    'social progress index',
    'urbanization',
    'united nations development programme',
    'walk free',
    'world giving index',
    'world happiness report',
    'dependencies by population',
    'dependencies by population density',
    'fragile states index',
    'homeless population',
    'guaranteed minimum income',
    'gun ownership',
    'incarceration rate',
    'intentional homicide rate',
    'public spending in tertiary education',
    'ethnic and cultural diversity level',
    'coal reserves',
    'natural gas proven reserves',
    'proven oil reserves',
    'thorium resources',
    'uranium reserves',
    'v-dem institute',
    'world justice project',
    'worldwide governance indicators',
    'global terrorism index',
    'consultation on rule-making',
    'reporters without borders',
    'freedom house',
    'transparency international',
    'united nations',
    'aircraft carriers',
    'small arms survey',
    'military expenditures',
    'military expenditure per capita',
    'military strength index',
    'number of military and paramilitary personnel',
    'index of national capability',
    'arms industry',
    'global militarization index',
    'nuclear weapons',
    'un peacekeepers',
    'level of military equipment',
    'aircraft carriers in service',
    'electricity production',
    'renewable electricity production',
    'uranium production',
    'platinum production',
    'gold production',
    'silver production',
    'copper production',
    'steel production',
    'primary aluminium production',
    'aluminium oxide production',
    'bismuth production',
    'mercury production',
    'bentonite production',
    'feldspar production',
    'lithium production',
    'palladium production',
    'manganese production',
    'magnesium production',
    'tin production',
    'zinc production',
    'salt production',
    'silicon production',
    'mineral production',
    'oil production',
    'natural gas production',
    'coal production',
    'bauxite production',
    'cement production',
    'wine-producing',
    'health insurance coverage',
    'quality of healthcare',
    'oecd health expenditure',
    'countries by hospital beds',
    'cancer rate',
    'risk of death from non-communicable disease',
    'euro health consumer index',
    'global hunger index',
    'life expectancy',
    'infant and under-five mortality rates',
    'average human height',
    'body mass index',
    'obesity rate',
    'hiv/aids adult prevalence rate',
    'tobacco use',
    'tobacco consumption',
    'alcohol consumption per capita',
    'suicide rate',
    'oldest people by country',
    'political and geographic',
    'countries and dependencies',
    'good country index',
    'linguistic diversity index',
    'futurebrand-country-index',
    'softpower30',
    'net exports',
    'exports per capita',
    'exports by country',
    'natural gas exports',
    'net oil exports',
    'oil exports',
    'refined petroleum exports',
    'gold exports',
    'copper exports',
    'iron-ore exports',
    'diamond exports',
    'ship exports',
    'electricity exports',
    'car exports',
    'truck exports',
    'automotive component exports',
    'aircraft component exports',
    'aircraft and spacecraft exports',
    'engine exports',
    'gas turbine exports',
    'computer exports',
    'integrated circuit exports',
    'telephone exports',
    'telecommunications equipment exports',
    'pharmaceutical exports',
    'maize exports',
    'wheat exports',
    'coffee exports',
    'raw cotton exports',
    'natural disaster risk',
    'climate change performance index',
    'environmental performance index',
    'environmental vulnerability index',
    'happy planet index',
    'ecological footprint',
    'sustainable society index',
    'the global 100',
    'freshwater withdrawal',
    'carbon dioxide emissions',
    'spending on education',
    'tertiary education attainment',
    'education index',
    'trends in international mathematics and science study',
    'programme for international student assessment',
    'progress in international reading literacy study',
    'literacy rate',
    'world intellectual property indicators',
    'secondary education attainment',
    'ef english proficiency index',
    'google code jam',
    'oecd',
    'international association for the evaluation of educational achievement',
    'educational testing service',
    'webometrics ranking of world universities',
    'nobel laureates',
    'world economic forum',
    'international institute for management development',
    'gini coefficient',
    'bloomberg innovation index',
    'global innovation index',
    'international innovation index',
    'index of economic freedom',
    'ease of doing business index',
    'indigo era',
    'economic complexity',
    'unemployment rate',
    'net international investment position per capita',
    'average wage',
    'minimum wage',
    'public debt',
    'wealth per adult',
    'credit rating',
    'government budget',
    'gross national income',
    'gni (ppp) per capita',
    'gni (nominal) per capita',
    'gdp sector composition',
    'gdp (nominal)',
    'gdp (nominal) per capita',
    'gdp (ppp) per capita',
    'gdp (ppp)',
    'real gdp growth rate',
    'tax revenue to gdp ratio',
    'largest historical gdp',
    'academy awards for best international feature film',
    'world heritage sites',
    'books published',
    'meat consumption',
    'beer consumption per capita',
    'milk consumption per capita',
    'natural gas consumption',
    'electricity consumption',
    'oil consumption',
    'cannabis use',
    'prevalence of opiates',
    'cocaine use',
    'irrigated land area',
    'producing countries of agricultural commodities',
    'plum production',
    'apple production',
    'artichoke production',
    'barley production',
    'cherry production',
    'cucumber production',
    'forest area',
    'garlic production',
    'papaya production',
    'pineapple production',
    'potato production',
    'soybean production',
    'tomato production',
    'economic freedom of the world',
    'index of freedom in the world',
    'press freedom index',
    'ciri human rights data project',
    'freedom in the world',
    'freedom of the press',
    'democracy ranking',
    'global enabling trade report',
    'bribe payers index',
    'global corruption barometer',
    'corruption perceptions index',
    'composite index of national capability',
    'privacy international',
    'democracy-dictatorship index',
    'lgbt rights by country or territory',
    'largest empires',
    'trade-to-gdp ratio',
    'global peace index',
    'global liveability ranking',
    'political terror scale',
    'global slavery index',
    'oecd better life index',
    'satisfaction with life index',
    'human capital index',
    'human development index',
    'inequality-adjusted human development index',
    'planetary pressures–adjusted human development index',
    'where-to-be-born index',
    'disposable household and per capita income',
    'long-term unemployment rate',
    'home ownership rate',
    'median income',
    'greenhouse gas emissions per person',
    'antidepressant consumption',
    'child development index',
    'countries by cancer rate',
    'global health security index',
    'hospital beds',
    'physicians',
    'prevalence of teenage pregnancy',
    'democracy index',
    'gender development index',
    'global competitiveness report',
    'multidimensional poverty index',
    'time devoted to leisure and personal care',
    'wealth inequality',
    'current account balance',
    'exports',
    'tariff rate',
    'leading trade partners',
    'received fdi',
    'fdi abroad',
    'gross fixed investment as percentage of gdp',
    'government budget (ppp)',
    'government spending as percentage of gdp',
    'government budget per capita',
    'pension fund',
    'sovereign wealth funds',
    'gold reserve',
    'foreign-exchange reserves',
    'tax rates',
    'inheritance tax rates',
    'central bank interest rates',
    'commercial bank prime lending rate',
    'exchange rates to the united states dollar',
    'inflation rate',
    'financial development index',
    'aid country donors',
    'gross national savings',
    'sovereign states by financial assets',
    'total wealth',
    'employment rate ',
    'Age of consent',
    'Age of candidacy',
    'Age of criminal responsibility',
    'Legal drinking age',
    'minimum driving ages',
    'Age of majority',
    'Marriageable age',
    'Retirement age',
    'School-leaving age',
    'Smoking age',
    'Voting age',
    'Legal working age',
    'Youth suffrage',
    'Suffrage',
    'Drug and precursor laws',
    'Mandatory retirement',
    'tobacco minimum purchase age',
    'psychoactive Amanita mushrooms',
    'Legal status of ayahuasca',
    'Legality of cannabis',
    'Annual cannabis use',
    'Adult lifetime cannabis',
    'Legal status of ibogaine',
    'psilocybin mushrooms',
    'Legal status of Salvia divinorum',
    'prevalence of cocaine use',
    'Legal status of cocaine',
    'status of methamphetamine',
    'prevalence of opiates use',
    'Legality of euthanasia',
    'intentional homicide rate by decade',
    'killings by law enforcement officers by country',
    'firearm-related death rate',
    'Estimated number of civilian guns per capita',
    'Percent of households with guns',
    'Corporal punishment in the home',
    'School corporal punishment',
    'Judicial corporal punishment',
    'Capital punishment by country',
    'Life imprisonment',
    'Legality of incest',
    'Pornography laws', "Legality of child pornography'", 'Legal status of fictional pornography depicting minors',
    'Laws regarding child sexual abuse',
    'Laws regarding rape',
    'Sodomy law',
    'Sex trafficking',
    'Trafficking of children',
    'Forced marriage',
    'Labour trafficking',
    'Trafficking for organ trade',
    'Abortion law',
    'Minors and abortion',
    'Adoption law',
    'International adoption',
    'Human_cloning law',
    'Legal status of human sterilization',
    'Surrogacy laws',
    'Censorship',
    'Book censorship',
    'books banned by governments',
    'Film censorship',
    'banned films',
    'Internet censorship',
    'Internet censorship and surveillance',
    'Political censorship',
    'Video game controversies',
    'banned video games', "Children's rights", 'Children in the military',
    'Intersex human rights',
    'LGBT rights',
    'Slavery',
    'Human trafficking',
    'Legality of bitcoin',
    'Animal rights',
    'Immigration law',
    'national legal systems',
    'WJP Rule of Law Index',
    'Application of Sharia',
    'world_governance_index',
    'universal health care',
    'social welfare spending',
    'age at first marriage',
    'age structure',
    'dependency ratio',
    'divorce demography',
    'immigrant population',
    'median age',
    'net migration rate',
    'number of households',
    'sex ratio',
    'urban population',
    'growth rate',
    'natural increase',
    'birth rate',
    'mortality rate',
    'total fertility rate',
    'past fertility rate',
    'public sector size',
    'number of billionaires',
    'type of financing',
    'percentage of population living in poverty',
    'number of millionaires',
    'total health expenditure per capita',
    'maternal mortality ratio',
    'stockpiling antiviral medications for pandemic influenza',
    'share of income of the richest one percent',
    'programme for the international assessment of adult competencies',
    'share of population with access to financial services',
    'development aid country donors',
    'official development assistance received',
    'employment rate',
    'human poverty index',
    'income equality',
    'labour force',
    'imports ',
    'bentonite',
    'fluorite production',
    'carbon dioxide emissions per capita',
    'greenhouse gas emissions',
    'motor vehicle production',
    'pulp and paper',
    'refrigerator',
    'washing machine',
    'zirconium',
    'yttrium',
    'tungsten',
    'titanium production',
    'tin',
    'thulium',
    'terbium',
    'tellurium',
    'tantalum',
    'strontium',
    'samarium',
    'ruthenium',
    'rubidium',
    'rhodium',
    'niobium',
    'nickel production',
    'neodymium',
    'molybdenum',
    'iron ore production',
    'indium',
    'holmium',
    'gadolinium',
    'erbium',
    'europium',
    'dysprosium',
    'chromium production',
    'copper smelter production',
    'cobalt',
    'aluminium oxide',
    'cadmium',
    'caesium',
    'barium',
    'antimony',
    'aluminium production',
    'electricity imports',
    'total primary energy consumption and production',
    'fossil fuel exporters',
    'geothermal power',
    'solar power',
    'wind power',
    'hydroelectric',
    'uranium mining',
    'nuclear power',
    'coal major consumers',
    'coal major exporters',
    'coal major importers',
    'recoverable shale gas',
    'natural gas imports',
    'oil',
    'oil imports',
    'gasoline and diesel usage and pricing'
]
